### ISSUE TITLE
Remove texture unit value in when passing textures to shaders

### ISSUE THREAD

**Issue by ifernandez** [Spontz/Phoenix#10]
In the editor script, a texture is passed to the shader this way:

uniform sampler2D screenTexture 0 /resources/textures/tv.jpg

The zero here indicates the texture unit. Subsequent textures must have values 1, 2, 3 etc... there. This should be automatically managed by the engine.

**Comment by perefm** [comment]
Solved in https://github.com/Spontz/Phoenix/commit/912ff42c194c2f44ee4471d0d577d82fc5450d67
