### ISSUE TITLE
Convert multiple spaces to a single space in formulas

### ISSUE THREAD

**Issue by ifernandez** [Spontz/Phoenix#9]
This:

uniform float        sunSize v1:=4;

should work the same way as:

uniform float sunSize v1:=4;

So we can indent properly.

**Comment by perefm** [comment]
I see the same in both formulas... what is the difference?

**Comment by ifernandez** [comment]
If you separate elements with more than one space character, it does not work

**Comment by perefm** [comment]
This is done in latest versions (v.1.2.0 and up)
